#!/usr/bin/env python3


def test_trustworthiness_vector():
    pass
    # TO DO: Throws error need to fix this
    # df = pd.read_csv("./data/bank.csv").select_dtypes(include=[int,float])

    # test_umap = umap.UMAP(
    #    n_neighbors=5,
    #    n_components=1).fit(df)

    # vectors = trustworthiness_vector(df.values, test_umap.embedding_, 5)

    # assert vectors.shape[0] == 5
    # assert vectors.max() == 1
